// Generated by scripts/build-editor-styles.mjs; do not edit.
export const editorClasses = {
  "compact": "svsurface-surface-editor svsurface-surface-editor--density_compact",
  "comfortable": "svsurface-surface-editor svsurface-surface-editor--density_comfortable"
} as const;
export const editorButtonClasses = {
  "secondary": "svsurface-surface-editor-button svsurface-surface-editor-button--variant_secondary",
  "primary": "svsurface-surface-editor-button svsurface-surface-editor-button--variant_primary"
} as const;
