import type { StrictResourceDefinition } from '../resource-types';

export const domainResources = [
  {
      name: 'skus',
      label: 'SKUs',
      icon: 'folder',
      group: 'Inventory',
      menuOrder: 20,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'sku', label: 'SKU', type: 'text', required: true, searchable: true, width: '140px' },
        { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'barcode', label: 'Barcode', type: 'text', searchable: true },
        { key: 'variant', label: 'Variant', type: 'text', searchable: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Paused', value: 'paused' },
            { label: 'Retired', value: 'retired' },
          ],
        },
      ],
      defaultSort: { field: 'sku', order: 'asc' },
    },
  {
      name: 'categories',
      label: 'Categories',
      icon: 'folder',
      group: 'Inventory',
      menuOrder: 30,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
        { key: 'code', label: 'Code', type: 'text', required: true, width: '100px' },
        { key: 'description', label: 'Description', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'suppliers',
      label: 'Suppliers',
      icon: 'users',
      group: 'Inventory',
      menuOrder: 40,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
        { key: 'contactName', label: 'Contact Name', type: 'text' },
        { key: 'email', label: 'Email', type: 'email' },
        { key: 'phone', label: 'Phone', type: 'phone' },
        { key: 'address', label: 'Address', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'warehouses',
      label: 'Warehouses',
      icon: 'home',
      group: 'Inventory',
      menuOrder: 50,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
        { key: 'code', label: 'Code', type: 'text', required: true, width: '120px' },
        { key: 'location', label: 'Location', type: 'text' },
        { key: 'capacity', label: 'Capacity', type: 'number', width: '110px' },
        { key: 'utilization', label: 'Utilization %', type: 'number', width: '130px' },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'notifications',
      label: 'Notification Center',
      icon: 'bell',
      group: 'Notifications',
      menuOrder: 140,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
        {
          key: 'channel',
          label: 'Channel',
          type: 'select',
          required: true,
          options: [
            { label: 'System', value: 'system' },
            { label: 'Inventory', value: 'inventory' },
            { label: 'Order', value: 'order' },
            { label: 'Security', value: 'security' },
          ],
        },
        {
          key: 'severity',
          label: 'Severity',
          type: 'select',
          required: true,
          options: [
            { label: 'Info', value: 'info' },
            { label: 'Warning', value: 'warning' },
            { label: 'Critical', value: 'critical' },
          ],
        },
        { key: 'recipientId', label: 'Recipient', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'read', label: 'Read', type: 'boolean', width: '90px' },
        { key: 'createdAt', label: 'Created', type: 'date', required: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'createdAt', order: 'desc' },
    },
  {
      name: 'store_client_products',
      label: 'Store Products',
      icon: 'shopping-bag',
      group: 'Store Operations',
      menuOrder: 260,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Product Name', type: 'text', required: true, searchable: true },
        { key: 'price', label: 'Price', type: 'number', required: true, width: '110px' },
        { key: 'category', label: 'Category', type: 'text', searchable: true },
        { key: 'rating', label: 'Rating', type: 'number', width: '100px' },
        { key: 'stock', label: 'Stock', type: 'number', width: '100px' },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'store_client_orders',
      label: 'Store Orders',
      icon: 'credit-card',
      group: 'Store Operations',
      menuOrder: 270,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
        { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Processing', value: 'processing' },
            { label: 'Shipped', value: 'shipped' },
            { label: 'Delivered', value: 'delivered' },
          ],
        },
        { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
      ],
      defaultSort: { field: 'orderDate', order: 'desc' },
    },
  {
      name: 'project_planning',
      label: 'Project Planning',
      icon: 'calendar',
      group: 'Planning',
      menuOrder: 280,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'milestone', label: 'Milestone', type: 'text', required: true, searchable: true },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'In Progress', value: 'in_progress' },
            { label: 'Review', value: 'review' },
            { label: 'Completed', value: 'completed' },
          ],
        },
        { key: 'confidence', label: 'Confidence %', type: 'number', width: '130px' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'dueDate', order: 'asc' },
    },
  {
      name: 'store_admin',
      label: 'Store Admin',
      icon: 'settings',
      group: 'Store Operations',
      menuOrder: 282,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'module', label: 'Module', type: 'text', required: true, searchable: true },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'In Progress', value: 'in_progress' },
            { label: 'Review', value: 'review' },
          ],
        },
        { key: 'targetDate', label: 'Target Date', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'targetDate', order: 'asc' },
    },
  {
      name: 'store_services',
      label: 'Store Services',
      icon: 'wrench',
      group: 'Store Operations',
      menuOrder: 284,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'serviceName', label: 'Service Name', type: 'text', required: true, searchable: true },
        {
          key: 'runtime',
          label: 'Runtime',
          type: 'select',
          required: true,
          options: [
            { label: 'Edge', value: 'edge' },
            { label: 'Queue', value: 'queue' },
            { label: 'Worker', value: 'worker' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'In Progress', value: 'in_progress' },
            { label: 'Review', value: 'review' },
          ],
        },
        { key: 'latencyBudgetMs', label: 'Latency Budget', type: 'number', width: '150px' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'serviceName', order: 'asc' },
    },
  {
      name: 'ai_prompt',
      label: 'AI Prompt',
      icon: 'sparkles',
      group: 'Intelligence',
      menuOrder: 286,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'promptName', label: 'Prompt Name', type: 'text', required: true, searchable: true },
        {
          key: 'audience',
          label: 'Audience',
          type: 'select',
          required: true,
          options: [
            { label: 'Developer', value: 'developer' },
            { label: 'Business', value: 'business' },
            { label: 'Educator', value: 'educator' },
            { label: 'Creative', value: 'creative' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'Review', value: 'review' },
            { label: 'Completed', value: 'completed' },
          ],
        },
        { key: 'usageCount', label: 'Usage Count', type: 'number', width: '120px' },
        { key: 'content', label: 'Content', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'usageCount', order: 'desc' },
    },
  {
      name: 'invoice_generator',
      label: 'Invoice Generator',
      icon: 'file',
      group: 'Operations',
      menuOrder: 288,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'templateName', label: 'Template Name', type: 'text', required: true, searchable: true },
        {
          key: 'channel',
          label: 'Channel',
          type: 'select',
          required: true,
          options: [
            { label: 'System', value: 'system' },
            { label: 'Order', value: 'order' },
            { label: 'Email', value: 'email' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'In Progress', value: 'in_progress' },
            { label: 'Review', value: 'review' },
          ],
        },
        { key: 'nextRunAt', label: 'Next Run', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'nextRunAt', order: 'asc' },
    },
  {
      name: 'billing_plans',
      label: 'Plans',
      icon: 'credit-card',
      group: 'Billing',
      menuOrder: 300,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'planName', label: 'Plan', type: 'text', required: true, searchable: true },
        {
          key: 'tier',
          label: 'Tier',
          type: 'select',
          required: true,
          options: [
            { label: 'Starter', value: 'starter' },
            { label: 'Pro', value: 'pro' },
            { label: 'Enterprise', value: 'enterprise' },
          ],
        },
        { key: 'priceMonthly', label: 'Monthly Price', type: 'number', required: true, width: '140px' },
        { key: 'seatsIncluded', label: 'Seats', type: 'number', width: '100px' },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Deprecated', value: 'deprecated' },
            { label: 'Draft', value: 'draft' },
          ],
        },
        { key: 'description', label: 'Description', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'priceMonthly', order: 'asc' },
    },
  {
      name: 'billing_invoices',
      label: 'Billing History',
      icon: 'file',
      group: 'Billing',
      menuOrder: 302,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'invoiceNumber', label: 'Invoice', type: 'text', required: true, searchable: true },
        { key: 'amount', label: 'Amount', type: 'number', required: true, width: '120px' },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Paid', value: 'paid' },
            { label: 'Pending', value: 'pending' },
            { label: 'Failed', value: 'failed' },
            { label: 'Refunded', value: 'refunded' },
          ],
        },
        { key: 'issuedDate', label: 'Issued', type: 'date', required: true },
        { key: 'periodStart', label: 'Period Start', type: 'date', showInList: false },
        { key: 'periodEnd', label: 'Period End', type: 'date', showInList: false },
      ],
      defaultSort: { field: 'issuedDate', order: 'desc' },
    },
  {
      name: 'billing_subscriptions',
      label: 'Subscriptions',
      icon: 'repeat',
      group: 'Billing',
      menuOrder: 304,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'subscriber', label: 'Subscriber', type: 'text', required: true, searchable: true },
        { key: 'planId', label: 'Plan', type: 'relation', resource: 'billing_plans', optionLabel: 'planName', optionValue: 'id', required: true },
        {
          key: 'billingCycle',
          label: 'Cycle',
          type: 'select',
          required: true,
          options: [
            { label: 'Monthly', value: 'monthly' },
            { label: 'Annual', value: 'annual' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Trialing', value: 'trialing' },
            { label: 'Canceled', value: 'canceled' },
            { label: 'Past Due', value: 'past_due' },
          ],
        },
        { key: 'renewsOn', label: 'Renews On', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'renewsOn', order: 'asc' },
    },
  {
      name: 'security_sessions',
      label: 'Current Sessions',
      icon: 'monitor',
      group: 'Security Operations',
      menuOrder: 310,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'device', label: 'Device', type: 'text', required: true, searchable: true },
        { key: 'ipAddress', label: 'IP Address', type: 'text', required: true, searchable: true, width: '140px' },
        { key: 'location', label: 'Location', type: 'text', searchable: true },
        { key: 'lastActive', label: 'Last Active', type: 'date', required: true },
        { key: 'current', label: 'Current', type: 'boolean', showInForm: false, showInList: false },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Idle', value: 'idle' },
            { label: 'Revoked', value: 'revoked' },
          ],
        },
      ],
      defaultSort: { field: 'lastActive', order: 'desc' },
    },
  {
      name: 'security_devices',
      label: 'Device Management',
      icon: 'smartphone',
      group: 'Security Operations',
      menuOrder: 312,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'deviceName', label: 'Device Name', type: 'text', required: true, searchable: true },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        {
          key: 'platform',
          label: 'Platform',
          type: 'select',
          required: true,
          options: [
            { label: 'iOS', value: 'ios' },
            { label: 'Android', value: 'android' },
            { label: 'macOS', value: 'macos' },
            { label: 'Windows', value: 'windows' },
            { label: 'Web', value: 'web' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Trusted', value: 'trusted' },
            { label: 'Pending', value: 'pending' },
            { label: 'Blocked', value: 'blocked' },
          ],
        },
        { key: 'enrolledAt', label: 'Enrolled', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'enrolledAt', order: 'desc' },
    },
  {
      name: 'security_allowed_ips',
      label: 'Allowed IPs',
      icon: 'shield',
      group: 'Security Operations',
      menuOrder: 314,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'cidr', label: 'IP / CIDR', type: 'text', required: true, searchable: true },
        { key: 'label', label: 'Label', type: 'text', searchable: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Allowed', value: 'allowed' },
            { label: 'Restricted', value: 'restricted' },
            { label: 'Disabled', value: 'disabled' },
          ],
        },
        { key: 'addedAt', label: 'Added', type: 'date', required: true },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'addedAt', order: 'desc' },
    },
  {
      name: 'referral_invites',
      label: 'Invite a Friend',
      icon: 'user-plus',
      group: 'Referrals',
      menuOrder: 320,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'inviteeEmail', label: 'Invitee Email', type: 'text', required: true, searchable: true },
        { key: 'inviterId', label: 'Inviter', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'code', label: 'Invite Code', type: 'text', searchable: true, width: '140px' },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Sent', value: 'sent' },
            { label: 'Accepted', value: 'accepted' },
            { label: 'Expired', value: 'expired' },
          ],
        },
        { key: 'sentAt', label: 'Sent', type: 'date', required: true },
        { key: 'acceptedAt', label: 'Accepted', type: 'date', showInList: false },
      ],
      defaultSort: { field: 'sentAt', order: 'desc' },
    },
] satisfies StrictResourceDefinition<
  | 'skus' | 'categories' | 'suppliers' | 'warehouses' | 'notifications'
  | 'store_client_products' | 'store_client_orders' | 'project_planning'
  | 'store_admin' | 'store_services' | 'ai_prompt' | 'invoice_generator'
  | 'billing_plans' | 'billing_invoices' | 'billing_subscriptions'
  | 'security_sessions' | 'security_devices' | 'security_allowed_ips'
  | 'referral_invites'
>[];
