<script lang="ts">
  import type { Snippet } from 'svelte'; import { onDestroy } from 'svelte'; import { Check, Copy } from '@lucide/svelte'; import { cn } from '../../utils.js'; import { useEnvironmentVariableContext } from './context.svelte.js';
  let { timeout = 2000, copyFormat = 'value', class: className = '', children, oncopy, onerror, disabled = false, ...rest }: { timeout?: number; copyFormat?: 'name' | 'value' | 'export'; class?: string; children?: Snippet<[boolean]>; oncopy?: () => void; onerror?: (error: Error) => void; disabled?: boolean; [key: string]: unknown } = $props();
  const context = useEnvironmentVariableContext(); let copied = $state(false); let timer: ReturnType<typeof setTimeout> | undefined;
  const text = $derived(copyFormat === 'name' ? context.name : copyFormat === 'export' ? `export ${context.name}="${context.value}"` : context.value);
  async function copyValue(): Promise<void> { if (disabled) return; if (typeof navigator === 'undefined' || !navigator.clipboard?.writeText) { onerror?.(new Error('Clipboard API not available')); return; } try { await navigator.clipboard.writeText(text); copied = true; oncopy?.(); if (timer) clearTimeout(timer); timer = setTimeout(() => { copied = false; }, timeout); } catch (error) { onerror?.(error instanceof Error ? error : new Error('Copy failed')); } }
  onDestroy(() => { if (timer) clearTimeout(timer); });
</script>
<button type="button" class={cn('inline-flex size-6 shrink-0 items-center justify-center rounded-md border-0 bg-transparent text-muted-foreground hover:bg-muted hover:text-foreground focus-visible:outline-2 focus-visible:outline-ring disabled:opacity-50', className)} aria-label={copied ? 'Copied environment variable' : `Copy ${copyFormat}`} {disabled} onclick={copyValue} {...rest}>{#if children}{@render children(copied)}{:else}{#if copied}<Check size={12} aria-hidden="true" />{:else}<Copy size={12} aria-hidden="true" />{/if}{/if}</button>
