import type { StrictResourceDefinition } from '../resource-types';

export const crmResources = [
  {
      name: 'crm_accounts',
      label: 'Customer Accounts',
      icon: 'briefcase',
      group: 'Customer Operations',
      menuOrder: 150,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'accountName', label: 'Account Name', type: 'text', required: true, searchable: true },
        {
          key: 'segment',
          label: 'Segment',
          type: 'select',
          required: true,
          options: [
            { label: 'Strategic', value: 'strategic' },
            { label: 'Growth', value: 'growth' },
            { label: 'Renewal', value: 'renewal' },
          ],
        },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        {
          key: 'health',
          label: 'Health',
          type: 'select',
          required: true,
          options: [
            { label: 'Healthy', value: 'healthy' },
            { label: 'Watch', value: 'watch' },
            { label: 'At Risk', value: 'at_risk' },
          ],
        },
        { key: 'annualValue', label: 'Annual Value', type: 'number', width: '130px' },
        { key: 'nextReview', label: 'Next Review', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'accountName', order: 'asc' },
    },
  {
      name: 'crm_contacts',
      label: 'Customer Contacts',
      icon: 'users',
      group: 'Customer Operations',
      menuOrder: 160,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'fullName', label: 'Full Name', type: 'text', required: true, searchable: true },
        { key: 'accountId', label: 'Account', type: 'relation', resource: 'crm_accounts', optionLabel: 'accountName', optionValue: 'id' },
        { key: 'email', label: 'Email', type: 'email', searchable: true },
        { key: 'phone', label: 'Phone', type: 'phone' },
        { key: 'roleTitle', label: 'Role Title', type: 'text', searchable: true },
        {
          key: 'influence',
          label: 'Influence',
          type: 'select',
          options: [
            { label: 'Decision Maker', value: 'decision_maker' },
            { label: 'Evaluator', value: 'evaluator' },
            { label: 'Operator', value: 'operator' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'New', value: 'new' },
            { label: 'Paused', value: 'paused' },
          ],
        },
        { key: 'lastTouchDate', label: 'Last Touch', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'lastTouchDate', order: 'desc' },
    },
  {
      name: 'crm_deals',
      label: 'Revenue Opportunities',
      icon: 'folder',
      group: 'Customer Operations',
      menuOrder: 170,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'dealName', label: 'Opportunity Name', type: 'text', required: true, searchable: true },
        { key: 'accountId', label: 'Account', type: 'relation', resource: 'crm_accounts', optionLabel: 'accountName', optionValue: 'id' },
        { key: 'contactId', label: 'Contact', type: 'relation', resource: 'crm_contacts', optionLabel: 'fullName', optionValue: 'id' },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        {
          key: 'stage',
          label: 'Stage',
          type: 'select',
          required: true,
          options: [
            { label: 'Discovery', value: 'discovery' },
            { label: 'Proposal', value: 'proposal' },
            { label: 'Negotiation', value: 'negotiation' },
            { label: 'Won', value: 'won' },
            { label: 'Lost', value: 'lost' },
          ],
        },
        { key: 'amount', label: 'Amount', type: 'number', required: true, width: '120px' },
        { key: 'probability', label: 'Probability %', type: 'number', width: '130px' },
        { key: 'closeDate', label: 'Close Date', type: 'date' },
        { key: 'nextStep', label: 'Next Step', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'closeDate', order: 'asc' },
    },
  {
      name: 'crm_activities',
      label: 'Customer Activities',
      icon: 'calendar',
      group: 'Customer Operations',
      menuOrder: 180,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'accountId', label: 'Account', type: 'relation', resource: 'crm_accounts', optionLabel: 'accountName', optionValue: 'id' },
        { key: 'contactId', label: 'Contact', type: 'relation', resource: 'crm_contacts', optionLabel: 'fullName', optionValue: 'id' },
        { key: 'dealId', label: 'Opportunity', type: 'relation', resource: 'crm_deals', optionLabel: 'dealName', optionValue: 'id' },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        {
          key: 'type',
          label: 'Type',
          type: 'select',
          options: [
            { label: 'Call', value: 'call' },
            { label: 'Demo', value: 'demo' },
            { label: 'Review', value: 'review' },
            { label: 'Email', value: 'email' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'Completed', value: 'completed' },
            { label: 'Follow Up', value: 'follow_up' },
          ],
        },
        { key: 'dueDate', label: 'Due Date', type: 'date' },
        { key: 'outcome', label: 'Outcome', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'dueDate', order: 'asc' },
    },
] satisfies StrictResourceDefinition<'crm_accounts' | 'crm_contacts' | 'crm_deals' | 'crm_activities'>[];
