import type { StrictResourceDefinition } from '../resource-types';

export const mailResources = [
  {
      name: 'mail_inbox',
      label: 'Mail Inbox',
      icon: 'mail',
      group: 'Mail Operations',
      menuOrder: 230,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'sender', label: 'Sender', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'date', label: 'Date', type: 'date', required: true },
        { key: 'unread', label: 'Unread', type: 'boolean', width: '90px' },
      ],
      defaultSort: { field: 'date', order: 'desc' },
    },
  {
      name: 'mail_draft',
      label: 'Mail Drafts',
      icon: 'file',
      group: 'Mail Operations',
      menuOrder: 240,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'to', label: 'To', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'updatedAt', label: 'Updated', type: 'date', required: true },
      ],
      defaultSort: { field: 'updatedAt', order: 'desc' },
    },
  {
      name: 'mail_sent',
      label: 'Mail Sent',
      icon: 'send',
      group: 'Mail Operations',
      menuOrder: 250,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'to', label: 'To', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'sentAt', label: 'Sent', type: 'date', required: true },
      ],
      defaultSort: { field: 'sentAt', order: 'desc' },
    },
  {
      name: 'mail_archive',
      label: 'Mail Archive',
      icon: 'folder',
      group: 'Mail Operations',
      menuOrder: 252,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'sender', label: 'Sender', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'date', label: 'Date', type: 'date', required: true },
        { key: 'unread', label: 'Unread', type: 'boolean', width: '90px' },
      ],
      defaultSort: { field: 'date', order: 'desc' },
    },
  {
      name: 'mail_snoozed',
      label: 'Mail Snoozed',
      icon: 'clock',
      group: 'Mail Operations',
      menuOrder: 254,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'sender', label: 'Sender', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'date', label: 'Date', type: 'date', required: true },
        { key: 'unread', label: 'Unread', type: 'boolean', width: '90px' },
      ],
      defaultSort: { field: 'date', order: 'desc' },
    },
  {
      name: 'mail_spam',
      label: 'Mail Spam',
      icon: 'alert-triangle',
      group: 'Mail Operations',
      menuOrder: 256,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'sender', label: 'Sender', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'date', label: 'Date', type: 'date', required: true },
        { key: 'unread', label: 'Unread', type: 'boolean', width: '90px' },
      ],
      defaultSort: { field: 'date', order: 'desc' },
    },
  {
      name: 'mail_trash',
      label: 'Mail Trash',
      icon: 'trash',
      group: 'Mail Operations',
      menuOrder: 258,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'sender', label: 'Sender', type: 'text', required: true, searchable: true },
        { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
        { key: 'body', label: 'Body', type: 'textarea', showInList: false },
        { key: 'date', label: 'Date', type: 'date', required: true },
        { key: 'unread', label: 'Unread', type: 'boolean', width: '90px' },
      ],
      defaultSort: { field: 'date', order: 'desc' },
    },
] satisfies StrictResourceDefinition<
  | 'mail_inbox' | 'mail_draft' | 'mail_sent' | 'mail_archive'
  | 'mail_snoozed' | 'mail_spam' | 'mail_trash'
>[];
