<script lang="ts">
  import type { Snippet } from 'svelte'; import type { HTMLButtonAttributes } from 'svelte/elements'; import { ArrowLeft, ArrowRight, CodeXml, RefreshCw } from '@lucide/svelte'; import { cn } from '../../utils.js'; import type { WebPreviewNavigationAction } from './context.svelte.js'; import { useWebPreviewContext } from './context.svelte.js';
  interface Props extends Omit<HTMLButtonAttributes, 'children' | 'class'> { action?: WebPreviewNavigationAction; tooltip?: string; class?: string; children?: Snippet; }
  let { action, tooltip, class: className = '', children, onclick, disabled, type = 'button', ...rest }: Props = $props(); const preview = useWebPreviewContext('WebPreviewNavigationButton');
  const actionDisabled = $derived(disabled ?? (action === 'back' ? !preview.canGoBack : action === 'forward' ? !preview.canGoForward : false));
  const label = $derived(tooltip ?? (action === 'back' ? 'Go back' : action === 'forward' ? 'Go forward' : action === 'reload' ? 'Reload preview' : action === 'console' ? 'Toggle console' : 'Preview action'));
  function activate(event: MouseEvent & { currentTarget: EventTarget & HTMLButtonElement }): void { onclick?.(event); if (event.defaultPrevented || !action) return; if (action === 'back') preview.back(); else if (action === 'forward') preview.forward(); else if (action === 'reload') preview.reload(); else preview.setConsoleOpen(!preview.consoleOpen); }
</script>
<button {...rest} {type} class={cn('svadmin-ai-web-part__navigation-button', className)} aria-label={label} title={label} disabled={actionDisabled} data-slot="web-preview-navigation-button" onclick={activate}>{#if children}{@render children()}{:else}{#if action === 'back'}<ArrowLeft size={15} aria-hidden="true" />{:else if action === 'forward'}<ArrowRight size={15} aria-hidden="true" />{:else if action === 'console'}<CodeXml size={15} aria-hidden="true" />{:else}<RefreshCw size={15} aria-hidden="true" />{/if}{/if}</button>
<style>.svadmin-ai-web-part__navigation-button { display: inline-flex; width: 2rem; height: 2rem; flex: none; align-items: center; justify-content: center; border: 0; border-radius: min(var(--radius, .5rem), .5rem); background: transparent; color: var(--muted-foreground, currentColor); cursor: pointer; }.svadmin-ai-web-part__navigation-button:hover:not(:disabled) { background: var(--muted, transparent); color: var(--foreground, currentColor); }.svadmin-ai-web-part__navigation-button:focus-visible { outline: 2px solid var(--ring, currentColor); outline-offset: 2px; }.svadmin-ai-web-part__navigation-button:disabled { cursor: not-allowed; opacity: .4; }</style>
