import type { StrictResourceDefinition } from '../resource-types';

export const peopleResources = [
  {
      name: 'users',
      label: 'Users',
      icon: 'users',
      group: 'User Management',
      menuOrder: 100,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
        { key: 'email', label: 'Email', type: 'email', required: true, searchable: true },
        { key: 'roleId', label: 'Role', type: 'relation', resource: 'roles', optionLabel: 'name', optionValue: 'id', required: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Invited', value: 'invited' },
            { label: 'Suspended', value: 'suspended' },
          ],
        },
        { key: 'department', label: 'Department', type: 'text', searchable: true },
        { key: 'lastActiveAt', label: 'Last Active', type: 'date' },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'roles',
      label: 'Roles',
      icon: 'shield',
      group: 'User Management',
      menuOrder: 110,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
        { key: 'slug', label: 'Slug', type: 'text', required: true, searchable: true, width: '160px' },
        { key: 'scope', label: 'Scope', type: 'text', required: true, searchable: true },
        {
          key: 'level',
          label: 'Level',
          type: 'select',
          required: true,
          options: [
            { label: 'Owner', value: 'owner' },
            { label: 'Manager', value: 'manager' },
            { label: 'Operator', value: 'operator' },
            { label: 'Viewer', value: 'viewer' },
          ],
        },
        { key: 'description', label: 'Description', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'permissions',
      label: 'Permissions',
      icon: 'key-round',
      group: 'User Management',
      menuOrder: 112,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'module', label: 'Module', type: 'text', required: true, searchable: true },
        { key: 'action', label: 'Action', type: 'text', required: true, searchable: true, width: '120px' },
        { key: 'roleId', label: 'Role', type: 'relation', resource: 'roles', optionLabel: 'name', optionValue: 'id', required: true },
        {
          key: 'effect',
          label: 'Effect',
          type: 'select',
          required: true,
          options: [
            { label: 'Allow', value: 'allow' },
            { label: 'Review', value: 'review' },
            { label: 'Deny', value: 'deny' },
          ],
        },
        { key: 'updatedAt', label: 'Updated', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'module', order: 'asc' },
    },
  {
      name: 'user_accounts',
      label: 'User Accounts',
      icon: 'settings',
      group: 'User Management',
      menuOrder: 114,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'userId', label: 'User', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id', required: true },
        {
          key: 'accountType',
          label: 'Account Type',
          type: 'select',
          required: true,
          options: [
            { label: 'Internal', value: 'internal' },
            { label: 'Partner', value: 'partner' },
            { label: 'Service', value: 'service' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Pending Review', value: 'pending_review' },
            { label: 'Locked', value: 'locked' },
          ],
        },
        { key: 'lastSignInAt', label: 'Last Sign In', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'lastSignInAt', order: 'desc' },
    },
  {
      name: 'user_logs',
      label: 'User Logs',
      icon: 'book-open',
      group: 'User Management',
      menuOrder: 116,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'userId', label: 'User', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'event', label: 'Event', type: 'text', required: true, searchable: true },
        { key: 'ipAddress', label: 'IP Address', type: 'text', width: '140px' },
        {
          key: 'severity',
          label: 'Severity',
          type: 'select',
          required: true,
          options: [
            { label: 'Info', value: 'info' },
            { label: 'Warning', value: 'warning' },
            { label: 'Critical', value: 'critical' },
          ],
        },
        { key: 'createdAt', label: 'Created', type: 'date', required: true },
        { key: 'details', label: 'Details', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'createdAt', order: 'desc' },
    },
  {
      name: 'user_settings',
      label: 'User Settings',
      icon: 'sliders-horizontal',
      group: 'User Management',
      menuOrder: 118,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'setting', label: 'Setting', type: 'text', required: true, searchable: true },
        { key: 'scope', label: 'Scope', type: 'text', required: true, searchable: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Enabled', value: 'enabled' },
            { label: 'Optional', value: 'optional' },
            { label: 'Disabled', value: 'disabled' },
          ],
        },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'updatedAt', label: 'Updated', type: 'date' },
      ],
      defaultSort: { field: 'setting', order: 'asc' },
    },
] satisfies StrictResourceDefinition<
  | 'users' | 'roles' | 'permissions' | 'user_accounts' | 'user_logs' | 'user_settings'
>[];
