import type { StrictResourceDefinition } from '../resource-types';

export const propertyResources = [
  {
      name: 'properties',
      label: 'Property Portfolio',
      icon: 'home',
      group: 'Property Operations',
      menuOrder: 190,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'propertyName', label: 'Property Name', type: 'text', required: true, searchable: true },
        { key: 'market', label: 'Market', type: 'text', required: true, searchable: true },
        {
          key: 'assetType',
          label: 'Asset Type',
          type: 'select',
          required: true,
          options: [
            { label: 'Multifamily', value: 'multifamily' },
            { label: 'Office', value: 'office' },
            { label: 'Retail', value: 'retail' },
            { label: 'Industrial', value: 'industrial' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Renovation', value: 'renovation' },
            { label: 'Listed', value: 'listed' },
            { label: 'Under Contract', value: 'under_contract' },
          ],
        },
        { key: 'units', label: 'Units', type: 'number', width: '100px' },
        { key: 'occupancy', label: 'Occupancy %', type: 'number', width: '130px' },
        { key: 'askingPrice', label: 'Asking Price', type: 'number', required: true },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'propertyName', order: 'asc' },
    },
  {
      name: 'property_agents',
      label: 'Property Advisors',
      icon: 'users',
      group: 'Property Operations',
      menuOrder: 200,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
        { key: 'email', label: 'Email', type: 'email', searchable: true },
        { key: 'phone', label: 'Phone', type: 'phone' },
        { key: 'territory', label: 'Territory', type: 'text', searchable: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'On Leave', value: 'on_leave' },
          ],
        },
        { key: 'capacityScore', label: 'Capacity Score', type: 'number', width: '140px' },
      ],
      defaultSort: { field: 'name', order: 'asc' },
    },
  {
      name: 'property_leads',
      label: 'Property Leads',
      icon: 'trending-up',
      group: 'Property Operations',
      menuOrder: 210,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'leadName', label: 'Lead Name', type: 'text', required: true, searchable: true },
        { key: 'propertyId', label: 'Property', type: 'relation', resource: 'properties', optionLabel: 'propertyName', optionValue: 'id' },
        { key: 'agentId', label: 'Advisor', type: 'relation', resource: 'property_agents', optionLabel: 'name', optionValue: 'id' },
        {
          key: 'source',
          label: 'Source',
          type: 'select',
          options: [
            { label: 'Referral', value: 'referral' },
            { label: 'Portal', value: 'portal' },
            { label: 'Walk In', value: 'walk_in' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          options: [
            { label: 'New', value: 'new' },
            { label: 'Qualified', value: 'qualified' },
            { label: 'Tour Scheduled', value: 'tour_scheduled' },
            { label: 'Offer', value: 'offer' },
            { label: 'Dormant', value: 'dormant' },
          ],
        },
        { key: 'budget', label: 'Budget', type: 'number', required: true },
        { key: 'targetMoveDate', label: 'Target Move Date', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'targetMoveDate', order: 'asc' },
    },
  {
      name: 'property_showings',
      label: 'Tour Schedule',
      icon: 'calendar',
      group: 'Property Operations',
      menuOrder: 220,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'showingNumber', label: 'Tour Number', type: 'text', required: true, searchable: true },
        { key: 'propertyId', label: 'Property', type: 'relation', resource: 'properties', optionLabel: 'propertyName', optionValue: 'id' },
        { key: 'leadId', label: 'Lead', type: 'relation', resource: 'property_leads', optionLabel: 'leadName', optionValue: 'id' },
        { key: 'agentId', label: 'Advisor', type: 'relation', resource: 'property_agents', optionLabel: 'name', optionValue: 'id' },
        { key: 'scheduledDate', label: 'Scheduled Date', type: 'date', required: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          options: [
            { label: 'Scheduled', value: 'scheduled' },
            { label: 'Completed', value: 'completed' },
            { label: 'Rescheduled', value: 'rescheduled' },
            { label: 'Cancelled', value: 'cancelled' },
          ],
        },
        { key: 'feedbackScore', label: 'Feedback Score', type: 'number', width: '140px' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'scheduledDate', order: 'asc' },
    },
] satisfies StrictResourceDefinition<
  | 'properties' | 'property_agents' | 'property_leads' | 'property_showings'
>[];
