import type { ResourceDefinition } from '@svadmin/core';
import { demoContracts } from './resource-contracts';
import { isDemoResource } from './resource-schemas';
import { definedOptions } from '@svadmin/core/options';
import { assertFeatureResourceCoverage } from './features/resource-registry';
import { showcaseResources } from './features/showcase/data';
import { caseResources } from './features/case/data';
import { catalogResources } from './features/catalog/data';
import { domainResources } from './features/domain/data';
import { operationsResources } from './features/operations/data';
import { planningResources } from './features/planning/data';
import { peopleResources } from './features/people/data';
import { calendarResources } from './features/calendar/data';
import { aiResources } from './features/ai/data';
import { crmResources } from './features/crm/data';
import { propertyResources } from './features/property/data';
import { mailResources } from './features/mail/data';

const resourceDefinitions: ResourceDefinition[] = [
  ...showcaseResources,
  ...caseResources,
  ...catalogResources,
  ...domainResources,
  ...operationsResources,
  ...planningResources,
  ...peopleResources,
  ...calendarResources,
  ...aiResources,
  ...crmResources,
  ...propertyResources,
  ...mailResources,
];

export const resources: ResourceDefinition[] = resourceDefinitions.map(resource => ({
  ...resource,
  ...(isDemoResource(resource.name) ? { contract: demoContracts[resource.name] } : {}),
}));
assertFeatureResourceCoverage(resources.filter((resource) => isDemoResource(resource.name)).map((resource) => resource.name));
const zhGroupLabels: Record<string, string> = {
  Inventory: '库存中心',
  Operations: '运营作业',
  'User Management': '组织权限',
  Planning: '计划日程',
  Intelligence: '智能助手',
  Notifications: '消息通知',
  'Customer Operations': '客户经营',
  'Property Operations': '资产运营',
  'Mail Operations': '邮件中心',
  'Store Operations': '商城应用',
  Billing: '账单',
  'Security Operations': '安全运营',
  Referrals: '推荐邀请',
};

const zhResourceLabels: Record<string, string> = {
  'Case Workspace': '案件工作台',
  Products: '商品档案',
  SKUs: 'SKU 管理',
  Categories: '品类管理',
  Suppliers: '供应商',
  Warehouses: '仓库',
  'Stock Movements': '库存流水',
  'Stock Transfers': '库存调拨',
  'Cycle Counts': '循环盘点',
  'Inventory Adjustments': '库存调整',
  'Reorder Rules': '补货规则',
  'Purchase Orders': '采购订单',
  'Sales Orders': '销售订单',
  Todo: '待办事项',
  Users: '用户列表',
  Roles: '角色管理',
  Permissions: '权限矩阵',
  'User Accounts': '用户账户',
  'User Logs': '用户日志',
  'User Settings': '用户设置',
  Calendar: '日程管理',
  'AI Chat': 'AI 对话',
  'Notification Center': '通知中心',
  'Customer Accounts': '客户账户',
  'Customer Contacts': '客户联系人',
  'Revenue Opportunities': '收入机会',
  'Customer Activities': '客户活动',
  'Property Portfolio': '资产组合',
  'Property Advisors': '资产顾问',
  'Property Leads': '资产线索',
  'Tour Schedule': '看房安排',
  'Mail Inbox': '收件箱',
  'Mail Drafts': '草稿箱',
  'Mail Sent': '已发送',
  'Mail Archive': '归档邮件',
  'Mail Snoozed': '稍后提醒',
  'Mail Spam': '垃圾邮件',
  'Mail Trash': '废纸篓',
  'Store Products': '商城商品',
  'Store Orders': '商城订单',
  'Project Planning': '项目计划',
  'Store Admin': '商城管理端',
  'Store Services': '商城服务端',
  'AI Prompt': 'AI 提示词',
  'Invoice Generator': '发票生成器',
  Plans: '套餐方案',
  'Billing History': '账单历史',
  Subscriptions: '订阅',
  'Current Sessions': '当前会话',
  'Device Management': '设备管理',
  'Allowed IPs': '允许的 IP',
  'Invite a Friend': '邀请好友',
};

const zhFieldLabels: Record<string, string> = {
  ID: 'ID',
  Name: '名称',
  SKU: 'SKU',
  Category: '品类',
  Supplier: '供应商',
  Price: '价格',
  Stock: '库存',
  'Min Stock': '最低库存',
  Description: '描述',
  Product: '商品',
  Barcode: '条码',
  Variant: '规格规格',
  Status: '状态',
  Code: '编码',
  'Contact Name': '联系人',
  Email: '电子邮箱',
  Phone: '联系电话',
  Address: '地址',
  Warehouse: '仓库',
  Location: '位置',
  Capacity: '容量',
  'Utilization %': '利用率 %',
  Quantity: '数量',
  Type: '类型',
  Note: '备注',
  Date: '日期',
  'Order Number': '订单号',
  'Total Amount': '总金额',
  'Order Date': '订单日期',
  'Delivery Date': '交付日期',
  'Customer Name': '客户名称',
  'Shipping Date': '发货日期',
  Title: '标题',
  Assignee: '负责人',
  'Due Date': '截止日期',
  Priority: '优先级',
  Completed: '完成',
  Notes: '说明',
  'Transfer Number': '调拨单号',
  'From Warehouse': '源仓库',
  'To Warehouse': '目的仓库',
  'Requested By': '申请人',
  'Requested Date': '申请日期',
  'Expected Date': '预计日期',
  'Count Number': '盘点单号',
  Owner: '负责人',
  'Scheduled Date': '计划日期',
  Scope: '范围',
  'Expected Items': '应盘项',
  'Counted Items': '已盘项',
  'Variance Items': '差异项',
  'Adjustment Number': '调整单号',
  'Quantity Change': '调整数量',
  Reason: '原因',
  'Approved By': '审批人',
  'Target Stock': '目标库存',
  'Reorder Qty': '补货数量',
  'Lead Time Days': '提前期天数',
  'Last Reviewed': '上次复核',
  Role: '角色',
  Department: '部门',
  'Last Active': '最近活跃',
  Level: '等级',
  Slug: '标识',
  Module: '模块',
  Action: '动作',
  Effect: '策略',
  User: '用户',
  'Account Type': '账户类型',
  'Last Sign In': '最近登录',
  Event: '事件',
  'IP Address': 'IP 地址',
  Details: '详情',
  Setting: '设置项',
  'Start Date': '开始日期',
  'End Date': '结束日期',
  Intent: '意图',
  'Last Message': '最后消息',
  Updated: '更新时间',
  Channel: '渠道',
  Severity: '严重性',
  Recipient: '接收人',
  Read: '已读',
  Created: '创建时间',
  Body: '内容',
  'Account Name': '账户名称',
  Segment: '分层',
  Health: '健康度',
  'Annual Value': '年度价值',
  'Next Review': '下次复盘',
  'Full Name': '姓名',
  Account: '账户',
  'Role Title': '角色头衔',
  Influence: '影响力',
  'Last Touch': '最近触达',
  'Opportunity Name': '机会名称',
  Contact: '联系人',
  Opportunity: '机会',
  Stage: '阶段',
  Amount: '金额',
  'Probability %': '概率 %',
  'Close Date': '预计成交日',
  'Next Step': '下一步',
  Subject: '主题',
  Outcome: '结果',
  'Property Name': '资产名称',
  Market: '市场',
  'Asset Type': '资产类型',
  Manager: '负责人',
  Units: '单元数',
  'Occupancy %': '出租率 %',
  'Asking Price': '挂牌价',
  Territory: '负责区域',
  'Capacity Score': '容量评分',
  'Lead Name': '线索名称',
  Property: '资产',
  Advisor: '顾问',
  Source: '来源',
  Budget: '预算',
  'Target Move Date': '目标入住日',
  Lead: '线索',
  'Tour Number': '看房编号',
  'Feedback Score': '反馈评分',
  Sender: '发件人',
  Unread: '未读',
  To: '收件人',
  Sent: '发送时间',
  'Product Name': '商品名称',
  Rating: '评分',
  Milestone: '里程碑',
  'Confidence %': '信心 %',
  'Target Date': '目标日期',
  'Service Name': '服务名称',
  Runtime: '运行时',
  'Latency Budget': '延迟预算',
  'Prompt Name': '提示词名称',
  Audience: '受众',
  'Usage Count': '使用次数',
  Content: '内容',
  'Template Name': '模板名称',
  'Next Run': '下次运行',
  Plan: '套餐',
  Tier: '等级',
  'Monthly Price': '月费',
  Seats: '席位',
  Invoice: '发票号',
  Issued: '开票日',
  'Period Start': '账期开始',
  'Period End': '账期结束',
  Subscriber: '订阅者',
  Cycle: '周期',
  'Renews On': '续费日',
  Device: '设备',
  'Device Name': '设备名称',
  Platform: '平台',
  Enrolled: '登记日',
  'IP / CIDR': 'IP / CIDR',
  Label: '标签',
  Added: '添加日',
  'Invitee Email': '被邀邮箱',
  Inviter: '邀请人',
  'Invite Code': '邀请码',
  Accepted: '接受日',
};

const zhOptionLabels: Record<string, string> = {
  Active: '启用',
  Paused: '暂停',
  Retired: '停用',
  Inbound: '入库',
  Outbound: '出库',
  Adjustment: '调整',
  Draft: '草稿',
  Ordered: '已下单',
  Received: '已收货',
  Cancelled: '已取消',
  Pending: '待处理',
  Processing: '处理中',
  Shipped: '已发货',
  High: '高',
  Medium: '中',
  Low: '低',
  Open: '打开',
  'In Progress': '进行中',
  Blocked: '阻塞',
  Done: '完成',
  Approved: '已批准',
  'In Transit': '运输中',
  Scheduled: '已计划',
  Reconciled: '已核对',
  Damage: '破损',
  'Cycle Count Variance': '盘点差异',
  'Return Correction': '退货修正',
  'System Correction': '系统修正',
  'Pending Approval': '待审批',
  Rejected: '已拒绝',
  Review: '待复核',
  Owner: '所有者',
  Manager: '经理',
  Operator: '操作员',
  Viewer: '只读',
  Allow: '允许',
  Deny: '拒绝',
  Internal: '内部',
  Service: '服务',
  'Pending Review': '待复核',
  Locked: '已锁定',
  Enabled: '已启用',
  Optional: '可选',
  Disabled: '已禁用',
  Purchase: '采购',
  'Cycle Count': '盘点',
  Receiving: '收货',
  Replenishment: '补货',
  Forecast: '预测',
  'Exception Review': '异常复核',
  'Policy Help': '政策帮助',
  Waiting: '等待中',
  Resolved: '已解决',
  System: '系统',
  Inventory: '库存',
  Order: '订单',
  Security: '安全',
  Info: '信息',
  Warning: '警告',
  Critical: '严重',
  Strategic: '战略',
  Growth: '增长',
  Renewal: '续约',
  Healthy: '健康',
  Watch: '观察',
  'At Risk': '风险',
  New: '新建',
  'Decision Maker': '决策人',
  Evaluator: '评估人',
  Discovery: '发现',
  Proposal: '方案',
  Negotiation: '谈判',
  Won: '已赢单',
  Lost: '已输单',
  Call: '电话',
  Demo: '演示',
  Email: '邮件',
  Planned: '已规划',
  Completed: '已完成',
  'Follow Up': '需跟进',
  Multifamily: '多户住宅',
  Office: '办公',
  Retail: '零售',
  Industrial: '工业',
  Renovation: '改造中',
  Listed: '已挂牌',
  'Under Contract': '签约中',
  'On Leave': '休假',
  Referral: '转介绍',
  Portal: '门户',
  'Walk In': '到访',
  Partner: '合作方',
  Qualified: '已确认',
  'Tour Scheduled': '已约看',
  Offer: '报价',
  Dormant: '休眠',
  Rescheduled: '已改期',
  Edge: '边缘',
  Queue: '队列',
  Worker: '工作器',
  Developer: '开发者',
  Business: '业务',
  Educator: '教育',
  Creative: '创意',
  Delivered: '已送达',
  'Starter': '入门',
  'Pro': '专业',
  'Enterprise': '企业',
  'Deprecated': '已弃用',
  'Paid': '已支付',
  'Failed': '失败',
  'Refunded': '已退款',
  'Monthly': '按月',
  'Annual': '按年',
  'Trialing': '试用中',
  'Canceled': '已取消',
  'Past Due': '逾期',
  'Idle': '空闲',
  'Revoked': '已撤销',
  'iOS': 'iOS',
  'Android': 'Android',
  'macOS': 'macOS',
  'Windows': 'Windows',
  'Web': '网页',
  'Trusted': '受信任',
  'Allowed': '允许',
  'Restricted': '受限',
  'Sent': '已发送',
  'Accepted': '已接受',
  'Expired': '已过期',
};

function localizeLabel(label: string, labels: Record<string, string>, locale: string): string {
  return locale === 'zh-CN' ? (labels[label] ?? label) : label;
}

export function createResources(locale: string): ResourceDefinition[] {
  return resources.map((resource) => definedOptions({
    ...resource,
    label: localizeLabel(resource.label, zhResourceLabels, locale),
    group: resource.group ? localizeLabel(resource.group, zhGroupLabels, locale) : resource.group,
    fields: resource.fields.map((field) => definedOptions({
      ...field,
      label: localizeLabel(field.label, zhFieldLabels, locale),
      options: field.options?.map((option) => ({
        ...option,
        label: localizeLabel(option.label, zhOptionLabels, locale),
      })),
    })),
  }));
}
