import type { StrictResourceDefinition } from '../resource-types';

export const operationsResources = [
  {
      name: 'stock_movements',
      label: 'Stock Movements',
      icon: 'trending-up',
      group: 'Operations',
      menuOrder: 60,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'quantity', label: 'Quantity', type: 'number', required: true, width: '110px' },
        {
          key: 'type',
          label: 'Type',
          type: 'select',
          required: true,
          options: [
            { label: 'Inbound', value: 'in' },
            { label: 'Outbound', value: 'out' },
            { label: 'Adjustment', value: 'adjustment' },
          ],
        },
        { key: 'note', label: 'Note', type: 'text' },
        { key: 'date', label: 'Date', type: 'date', required: true, width: '130px' },
      ],
      defaultSort: { field: 'date', order: 'desc' },
    },
  {
      name: 'purchase_orders',
      label: 'Purchase Orders',
      icon: 'download',
      group: 'Operations',
      menuOrder: 100,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
        { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id', required: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Ordered', value: 'ordered' },
            { label: 'Received', value: 'received' },
            { label: 'Cancelled', value: 'cancelled' },
          ],
        },
        { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
        { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
        { key: 'deliveryDate', label: 'Delivery Date', type: 'date' },
      ],
      defaultSort: { field: 'orderDate', order: 'desc' },
    },
  {
      name: 'sales_orders',
      label: 'Sales Orders',
      icon: 'credit-card',
      group: 'Operations',
      menuOrder: 110,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
        { key: 'customerName', label: 'Customer Name', type: 'text', required: true, searchable: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Pending', value: 'pending' },
            { label: 'Processing', value: 'processing' },
            { label: 'Shipped', value: 'shipped' },
            { label: 'Cancelled', value: 'cancelled' },
          ],
        },
        { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
        { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
        { key: 'shippingDate', label: 'Shipping Date', type: 'date' },
      ],
      defaultSort: { field: 'orderDate', order: 'desc' },
    },
  {
      name: 'stock_transfers',
      label: 'Stock Transfers',
      icon: 'repeat',
      group: 'Operations',
      menuOrder: 70,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'transferNumber', label: 'Transfer Number', type: 'text', required: true, searchable: true },
        { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'fromWarehouseId', label: 'From Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'toWarehouseId', label: 'To Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'quantity', label: 'Quantity', type: 'number', required: true, width: '110px' },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Approved', value: 'approved' },
            { label: 'In Transit', value: 'in_transit' },
            { label: 'Received', value: 'received' },
            { label: 'Cancelled', value: 'cancelled' },
          ],
        },
        { key: 'requestedById', label: 'Requested By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'requestedDate', label: 'Requested Date', type: 'date', required: true },
        { key: 'expectedDate', label: 'Expected Date', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'requestedDate', order: 'desc' },
    },
  {
      name: 'cycle_counts',
      label: 'Cycle Counts',
      icon: 'clipboard-check',
      group: 'Operations',
      menuOrder: 80,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'countNumber', label: 'Count Number', type: 'text', required: true, searchable: true },
        { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'scheduledDate', label: 'Scheduled Date', type: 'date', required: true },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Scheduled', value: 'scheduled' },
            { label: 'In Progress', value: 'in_progress' },
            { label: 'Reconciled', value: 'reconciled' },
            { label: 'Cancelled', value: 'cancelled' },
          ],
        },
        { key: 'scope', label: 'Scope', type: 'text', searchable: true },
        { key: 'expectedItems', label: 'Expected Items', type: 'number', width: '130px' },
        { key: 'countedItems', label: 'Counted Items', type: 'number', width: '130px' },
        { key: 'varianceItems', label: 'Variance Items', type: 'number', width: '130px' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'scheduledDate', order: 'asc' },
    },
  {
      name: 'inventory_adjustments',
      label: 'Inventory Adjustments',
      icon: 'sliders-horizontal',
      group: 'Operations',
      menuOrder: 90,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'adjustmentNumber', label: 'Adjustment Number', type: 'text', required: true, searchable: true },
        { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'quantityChange', label: 'Quantity Change', type: 'number', required: true, width: '140px' },
        {
          key: 'reason',
          label: 'Reason',
          type: 'select',
          required: true,
          options: [
            { label: 'Damage', value: 'damage' },
            { label: 'Cycle Count Variance', value: 'cycle_count_variance' },
            { label: 'Return Correction', value: 'return_correction' },
            { label: 'System Correction', value: 'system_correction' },
          ],
        },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Pending Approval', value: 'pending_approval' },
            { label: 'Approved', value: 'approved' },
            { label: 'Rejected', value: 'rejected' },
          ],
        },
        { key: 'requestedById', label: 'Requested By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'approvedById', label: 'Approved By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
        { key: 'requestedDate', label: 'Requested Date', type: 'date', required: true },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'requestedDate', order: 'desc' },
    },
  {
      name: 'reorder_rules',
      label: 'Reorder Rules',
      icon: 'alert-triangle',
      group: 'Operations',
      menuOrder: 95,
      fields: [
        { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
        { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
        { key: 'minStock', label: 'Min Stock', type: 'number', required: true, width: '110px' },
        { key: 'targetStock', label: 'Target Stock', type: 'number', required: true, width: '120px' },
        { key: 'reorderQuantity', label: 'Reorder Qty', type: 'number', required: true, width: '120px' },
        { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id' },
        { key: 'leadTimeDays', label: 'Lead Time Days', type: 'number', width: '140px' },
        {
          key: 'status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Review', value: 'review' },
            { label: 'Paused', value: 'paused' },
          ],
        },
        { key: 'lastReviewedAt', label: 'Last Reviewed', type: 'date' },
        { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
      ],
      defaultSort: { field: 'lastReviewedAt', order: 'desc' },
    },
] satisfies StrictResourceDefinition<
  | 'stock_movements' | 'purchase_orders' | 'sales_orders' | 'stock_transfers'
  | 'cycle_counts' | 'inventory_adjustments' | 'reorder_rules'
>[];
